{"trial_id": "1", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "optimizer", "default": "adam", "conditions": [], "values": ["adam", "sgd", "rmsprop", "adadelta"], "ordered": false}}], "values": {"optimizer": "sgd"}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\Users\\hp\\gitdemo\\DATA-SCIENCE\\venv\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\hp\\gitdemo\\DATA-SCIENCE\\venv\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\hp\\gitdemo\\DATA-SCIENCE\\venv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"C:\\Users\\hp\\gitdemo\\DATA-SCIENCE\\venv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 232, in _build_and_fit_model\n    model = self._try_build(hp)\n  File \"C:\\Users\\hp\\gitdemo\\DATA-SCIENCE\\venv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 164, in _try_build\n    model = self._build_hypermodel(hp)\n  File \"C:\\Users\\hp\\gitdemo\\DATA-SCIENCE\\venv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 155, in _build_hypermodel\n    model = self.hypermodel.build(hp)\n  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_11500\\1528853778.py\", line 2, in build_model\n    model.add(Dense(32,activation='relu',input_dim=8))\n  File \"C:\\Users\\hp\\gitdemo\\DATA-SCIENCE\\venv\\lib\\site-packages\\tensorflow\\python\\trackable\\base.py\", line 204, in _method_wrapper\n    result = method(self, *args, **kwargs)\n  File \"C:\\Users\\hp\\gitdemo\\DATA-SCIENCE\\venv\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\hp\\gitdemo\\DATA-SCIENCE\\venv\\lib\\site-packages\\keras\\src\\engine\\sequential.py\", line 192, in add\n    raise ValueError(\nValueError: All layers added to a Sequential model should have unique names. Name \"dense\" is already the name of a layer in this model. Update the `name` argument to pass a unique name.\n"}